name = "verso-snippets"
version = "0.1.0"
defaultTargets = ["Snippet", "generate-snippet"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.29.0"

[[lean_lib]]
name = "Snippet"
srcDir = "verso-snippets"

[[lean_exe]]
name = "generate-snippet"
root = "Main"
srcDir = "verso-snippets"

[[lean_exe]]
name = "wrap-lean"
root = "WrapLean"
srcDir = "verso-snippets"
